spring.jackson.property-naming-strategy=SNAKE_CASE

spring.datasource.url=jdbc:postgresql://localhost:5432/waypoint
spring.datasource.username=postgres
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
